import { Product, TargetingInputs, TargetingMetrics, TargetingSegment } from "@/lib/types";

const baseTargeting: TargetingInputs = {
  ageMin: "24",
  ageMax: "44",
  genders: ["All"],
  includeRegions: "United States, Canada, United Kingdom",
  excludeRegions: "Russia, China",
  languages: "English",
  interests: "Sneakers, Running, Fitness wearables, Urban lifestyle",
  intentSignals: "running shoes, commuter gear, sportswear reviews",
  industries: "Retail, Consumer Goods, Lifestyle",
  companySize: "Mid-market (200-1000)",
  jobSeniority: "Manager, Director, VP",
  jobFunctions: "Marketing, Growth, Product",
  devices: ["Mobile", "Desktop"],
  platforms: ["iOS", "Android", "Web"],
  placements: ["Homepage", "Product pages", "Blog"],
  contentTopics: "Lifestyle, Fitness, Apparel",
  brandSafetyLevel: "Standard",
  excludedBrands: "Competitor X, Competitor Y",
  excludedKeywords: "free, cheap, discount",
  frequencyCap: "3 / day",
  objective: "Awareness",
};

export const seedProducts: Product[] = [
  {
    id: "p-1",
    name: "CloudWalk Sneakers",
    sku: "CW-2024-001",
    category: "Apparel",
    advertiser: "CloudWalk",
    status: "Approved",
    launchDate: "2026-03-12",
    priceRange: "$80–$120",
    updatedAt: "Feb 2, 2026",
    brandTone: "Professional",
    description: "Premium lifestyle sneakers positioned for urban commuters.",
    targeting: {
      ...baseTargeting,
      includeRegions: "United States, Canada, United Kingdom",
      excludeRegions: "Russia, China",
      interests: "Sneakers, Streetwear, Running, Lifestyle shopping",
      intentSignals: "urban commuter shoes, performance sneakers, streetwear drops",
      devices: ["Mobile", "Desktop"],
      placements: ["Homepage", "Product pages", "Blog"],
      contentTopics: "Lifestyle, Footwear, Streetwear",
      excludedBrands: "Competitor X, Budget footwear brands",
      excludedKeywords: "cheap, discount, clearance",
      frequencyCap: "3 / day",
      objective: "Awareness",
    },
    sentiment: {
      netSentiment: 68,
      confidence: 91,
      volume: "142k mentions / 30d",
      momentum: "+12%",
      distribution: { positive: 64, neutral: 26, negative: 10 },
      drivers: [
        "Comfort + durability performance tests",
        "Urban commuter lifestyle endorsements",
        "Influencer styling content",
      ],
      risks: ["Price sensitivity in student cohorts", "Sizing consistency questions"],
      insights: [
        "Strong affinity with tech professionals in metro regions",
        "Peak engagement occurs mid-week commute windows",
      ],
      trend: [52, 55, 58, 60, 63, 66, 68, 70],
      sources: ["Social listening", "Review sites", "Retail partner feedback"],
    },
  },
  {
    id: "p-2",
    name: "HydroBottle 2.0",
    sku: "HB-2024-042",
    category: "Fitness",
    advertiser: "HydroBottle",
    status: "Ready for View",
    launchDate: "2026-02-20",
    priceRange: "$24–$38",
    updatedAt: "Feb 1, 2026",
    brandTone: "Playful",
    description: "Reusable bottle for endurance athletes and wellness routines.",
    targeting: {
      ...baseTargeting,
      ageMin: "20",
      ageMax: "45",
      includeRegions: "United States, Australia, Canada",
      excludeRegions: "China, Russia",
      interests: "Fitness, Wellness, Running, Outdoor gear, Health apps",
      intentSignals: "hydration trackers, endurance training, wellness challenges",
      industries: "Wellness, Fitness, Sports Retail",
      companySize: "SMB (50-200)",
      jobSeniority: "Manager, IC",
      jobFunctions: "Marketing, Partnerships",
      placements: ["Homepage", "Product pages", "Email"],
      contentTopics: "Fitness, Wellness, Outdoor",
      frequencyCap: "4 / day",
      objective: "Consideration",
    },
    sentiment: {
      netSentiment: 72,
      confidence: 88,
      volume: "98k mentions / 30d",
      momentum: "+8%",
      distribution: { positive: 69, neutral: 22, negative: 9 },
      drivers: ["Sustainability messaging", "Athlete partnerships", "Colorway drops"],
      risks: ["Concerns about insulation performance"],
      insights: [
        "High engagement from health apps and community challenges",
        "Conversion lift when paired with hydration tips content",
      ],
      trend: [54, 56, 60, 62, 64, 68, 70, 72],
      sources: ["Social listening", "App partner surveys", "Retail reviews"],
    },
  },
  {
    id: "p-3",
    name: "SonicPro Headphones",
    sku: "SP-2024-089",
    category: "Electronics",
    advertiser: "SonicPro",
    status: "Ready for View",
    launchDate: "2026-04-05",
    priceRange: "$199–$249",
    updatedAt: "Jan 29, 2026",
    brandTone: "Luxury",
    description: "High-fidelity audio for audiophile communities.",
    targeting: {
      ...baseTargeting,
      ageMin: "18",
      ageMax: "40",
      includeRegions: "United States, Germany, Japan, United Kingdom",
      excludeRegions: "India, Russia",
      interests: "Audio gear, Tech reviews, Gaming, Smart devices, Hi-fi",
      intentSignals: "noise-canceling, lossless audio, premium headphones",
      industries: "Consumer Electronics, Gaming, Media",
      companySize: "Enterprise (1000+)",
      jobSeniority: "Director, VP",
      jobFunctions: "Product, Engineering, Marketing",
      objective: "Consideration",
      excludedKeywords: "discount, cheap, clearance",
      placements: ["Homepage", "Product pages", "Blog", "Email"],
      contentTopics: "Audio, Technology, Gaming",
    },
    sentiment: {
      netSentiment: 61,
      confidence: 86,
      volume: "76k mentions / 30d",
      momentum: "+6%",
      distribution: { positive: 58, neutral: 30, negative: 12 },
      drivers: ["Audio fidelity reviews", "Studio-grade endorsements"],
      risks: ["Battery life concerns", "Price comparisons vs competitors"],
      insights: [
        "Higher sentiment among creators and pro audio communities",
        "Late-night browsing correlates with higher add-to-cart rate",
      ],
      trend: [48, 50, 52, 56, 58, 59, 60, 61],
      sources: ["Tech reviews", "Creator forums", "Social listening"],
    },
  },
  {
    id: "p-4",
    name: "ZenGlow Candle",
    sku: "ZG-2024-005",
    category: "Home Decor",
    advertiser: "ZenGlow",
    status: "Ready for View",
    launchDate: "2026-02-28",
    priceRange: "$30–$45",
    updatedAt: "Jan 30, 2026",
    brandTone: "Bold",
    description: "Minimalist scent collection for modern interiors.",
    targeting: {
      ...baseTargeting,
      ageMin: "25",
      ageMax: "54",
      includeRegions: "United States, France, United Kingdom",
      excludeRegions: "China, Russia",
      interests: "Home decor, Interior design, Lifestyle, Premium candles",
      intentSignals: "minimalist decor, mood lighting, aromatherapy",
      industries: "Home Decor, Lifestyle",
      companySize: "SMB (10-50)",
      jobSeniority: "Manager, Director",
      jobFunctions: "Marketing, Brand, Merchandising",
      placements: ["Homepage", "Blog", "Email"],
      contentTopics: "Home decor, Wellness, Lifestyle",
      frequencyCap: "4 / day",
      objective: "Awareness",
    },
    sentiment: {
      netSentiment: 66,
      confidence: 84,
      volume: "52k mentions / 30d",
      momentum: "+9%",
      distribution: { positive: 61, neutral: 28, negative: 11 },
      drivers: ["Minimalist packaging", "Seasonal scent drops"],
      risks: ["Shipping delays during peak season"],
      insights: [
        "Strong resonance with premium home decor communities",
        "Engagement spikes with behind-the-scenes content",
      ],
      trend: [46, 49, 53, 57, 60, 63, 64, 66],
      sources: ["Lifestyle blogs", "Marketplace reviews", "Social listening"],
    },
  },
];

export const seedSegments: TargetingSegment[] = [
  {
    id: "s-1",
    title: "Tech Enthusiasts",
    tags: ["High Intent", "Early Adopters"],
    confidence: 96,
    rationale:
      "Shows 4.2x higher conversion propensity compared to baseline with significant overlap in high-LTV cohorts.",
    reach: "820k–1.1M",
    cpmIndex: "Standard",
  },
  {
    id: "s-2",
    title: "Luxury Shoppers",
    tags: ["Affluent", "Designer Interest"],
    confidence: 89,
    rationale:
      "Income signals and interest mapping suggest strong engagement potential for premium positioning.",
    reach: "620k–900k",
    cpmIndex: "Premium",
  },
  {
    id: "s-3",
    title: "Urban Fitness",
    tags: ["Active", "Mobile"],
    confidence: 92,
    rationale:
      "High engagement with wellness content and in-app purchases. Best for mobile-first placements.",
    reach: "540k–770k",
    cpmIndex: "Efficient",
  },
];

export const seedMetrics: TargetingMetrics = {
  impressionGoal: "2.5M",
  estimatedReach: "1.85M",
  confidence: 92,
  objective: "Awareness",
  updatedAt: "Just now",
};
